# Uncomment the next line to define a global platform for your project
 platform :ios, '13.3'

target 'MOBT-1-Clean-Code' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MOBT-1-Clean-Code
  pod 'SwiftLint'
  
end
